name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bjand49/dls-pos-frontend
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: bjand49
        password: ${{ secrets.DOCKER_PAT }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: bjand49/dls-pos-frontend
        
    - name: Push Docker image
      run: docker push bjand49/dls-pos-frontend
